FROM debian:stretch

ENV HORIZON_BASEDIR=/opt/horizon \
    KEYSTONE_URL='http://keystone:5000/v2' \
    APACHE_RUN_USER=www-data \
    APACHE_RUN_GROUP=www-data \
    APACHE_PID_FILE=/var/run/apache2/apache2.pid \
    APACHE_RUN_DIR=/var/run/apache2 \
    APACHE_LOCK_DIR=/var/lock/apache2 \
    APACHE_LOG_DIR=/var/log/apache2 \
    LANG=C \
    VERSION=stable/stein

EXPOSE 80

RUN \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y \
    apache2 libapache2-mod-wsgi-py3 python3-pip python3-dev git gcc libnss3-dev pkg-config gettext

RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip

RUN pip install --upgrade pip && \
    pip install python-memcached && \
    pip install django-widget-tweaks

WORKDIR ${HORIZON_BASEDIR}

RUN git clone --branch $VERSION --depth 1 https://github.com/klinux/horizon.git ${HORIZON_BASEDIR} && \
    pip install -c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=${VERSION} -r requirements.txt

RUN mv local_settings_prod.py openstack_dashboard/local/local_settings.py

RUN ./manage.py compilemessages && \
    ./manage.py collectstatic --noinput && \
    ./manage.py compress && \
    ./manage.py make_web_conf --wsgi

RUN rm -rf /etc/apache2/sites-enabled/* && \
    ./manage.py make_web_conf --processes 4 --apache > /etc/apache2/sites-enabled/horizon.conf && \
    sed -i 's/<VirtualHost \*.*/<VirtualHost _default_:80>/g' /etc/apache2/sites-enabled/horizon.conf && \
    chown -R www-data:www-data ${HORIZON_BASEDIR} && \
    python -m compileall $HORIZON_BASEDIR && \
    sed -i '/ErrorLog/c\    ErrorLog \/dev\/stderr' /etc/apache2/sites-enabled/horizon.conf && \
    sed -i '/CustomLog/c\    CustomLog \/dev\/stdout combined' /etc/apache2/sites-enabled/horizon.conf && \
    sed -i '/ErrorLog/c\    ErrorLog \/dev\/stderr' /etc/apache2/apache2.conf

RUN apt-get remove -y git gcc libnss3-dev python3-dev && \
    apt-get autoremove -y

CMD /usr/sbin/apache2 -DFOREGROUND
