version: '3'

services:
  horizon:
      image: horizon-cloudwise
      volumes:
        - ./local_settings.py:/opt/horizon/openstack_dashboard/local/local_settings.py:ro
      ports:
        - 8000:80
