version: '3'

services:
  horizon:
      image: horizon
      entrypoint: tox -e runserver 0.0.0.0:5000
      volumes:
        - ./:/app/
      ports:
        - 5000:5000

  horizon-prod:
      image: horizon-cloudwise
      volumes:
        - ./local_settings_prod.py:/opt/horizon/openstack_dashboard/local/local_settings.py:ro
      ports:
        - 8000:80
